### PR TITLE
Added variables and mixins details

### PR DESCRIPTION
**Pull request by SomMeri**
Added documentation for:
- lazy loading of variables,
- semicolon as mixins parameter - also changed comma into semicolon in examples,
- what happens when multiple mixins use the same name and number of parameters,
- string interpolation inside escaped values
- media queries as variables.

Most of these are new and I found about them in issue database.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Great! thanks for this. we are in process of updating the wiki/docs and website, and I just wanted to let you know that we will be sure to get your changes merged in at some point during the update. (even if it doesn't seem like anything's happening :-)

Any additions like this are sincerely appreciated, so thanks again!

**Comment by SomMeri** [comment]
Thank you for the feedback, it is more motivating when pull request are listened to. 

Added also:
- the keyword !important after mixin call.

**Comment by lukeapage** [comment]
@SomMeri your input in less.js has been great.. It really helps having someone try to figure out the language from a strict compiler point of view.

Now I've released a beta of 1.4.0 I was planning to pull the pulls tomorrow and where appropriate signify if the behaviour is only in 1.4.0

Thanks!

**Comment by lukeapage** [comment]
pulled thanks

**Pull request closed without merging**
