### PR TITLE
Various

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
**bump**

**Comment by XhmikosR** [comment]
I guess there's no interest for this.

**Comment by lukeapage** [comment]
yeh I'm sorry we've just been hard at work at re-writing the site. I probably should have just pulled it in the meantime, but it slipped by..

**Comment by XhmikosR** [comment]
Feel free to merge it now if there are no conflicts. It's been so long since I made the changes that I don't even remember the details...

**Pull request closed without merging**
