### PR TITLE
Update docs to encourage only performing operations within parentheses

### PR DESCRIPTION
**Pull request by dmcass**
Pretty much exactly what the title says. Let me know if you want me to change anything.

### CODE REVIEW

**Comment by EvanLovely** [comment]
Out of curiosity, why? I see that you said this in the commit:

> Operations should only be performed within parentheses in order to ensure compatibility with CSS.

**Comment by dmcass** [comment]
Because LESS will be moving to that model. In a future version of LESS any operations performed outside of parentheses will not be evaluated. CSS is using forward slash to delimit multiple values of the same type (elliptical border-radius, background shorthand), and they may use other "operators" in the future to do something different. Encouraging people to wrap their operations in parentheses now means less breakage in the future.

**Comment by EvanLovely** [comment]
Awesome, thanks for the background! Good habits now that make less stress in the future sounds good to me!

**Comment by lukeapage** [comment]
great, will commit this when I do 1.3.1

**Comment by lukeapage** [comment]
pulled.

**Pull request closed without merging**
