### PR TITLE
Update docs for new color functions

### PR DESCRIPTION
**Pull request by Synchro**
Document new color functions introduced in [#730](http//github.com/cloudhead/less.js/issues/730) and [#803](http//github.com/cloudhead/less.js/issues/803) in less.js.

Also some minor amends to make use of color functions a bit clearer and safer - applying spin to a grey value will do nothing because it has no saturation, so any hue value will be lost in the conversion back to RGB. This has been a source of support issues.

### CODE REVIEW

**Comment by lukeapage** [comment]
1. how do you get to reference.md?
2. Think I'll delete the testing file.. it is wrong
3. is this ready to commit when I update for 1.3.1?

**Comment by Synchro** [comment]
```
how do you get to reference.md?
```

No idea! This has some bearing on my question about where these docs should go.

```
Think I'll delete the testing file.. it is wrong
```

I've done that in my fork.

```
is this ready to commit when I update for 1.3.1?
```

The docs include the hsv functions which I don't think have been pulled in yet, and they are missing the docs on color blending functions that Rubens said he was doing. Otherwise yes. This morning I did a load of testing and changes to make sure that the examples actually do what they say and I think it's now complete apart from those two things.

Looking in functions.js makes me think that we're not very consistent in how percentages are handled, should probably add some more test cases.

**Comment by lukeapage** [comment]
I'm wondering whether the functions section should be removed entirely and should link to a new page which has your reference information in them? Or maybe cut down to one or two examples and then link to your pages?

Will you do a new pull request with the changes you mention or shall I take this one first?

**Comment by Synchro** [comment]
Not quite sure what you mean about the functions section?

Take this pull first, other changes can come later. My only reservation is that the blend modes have placeholder titles but no content. Are you happy for me to pull [#918](https://github.com/cloudhead/less.js/pull/918) so the HSV docs are then true?

**Comment by matthew-dean** [comment]
Did the fade definition change?

**Comment by Synchro** [comment]
No?

**Comment by matthew-dean** [comment]
Ok, never mind. Hey, was poking at the new code in 1.3.1 today. Is there a reason the default threshold on the new contrast function appears to be 0.43?

**Comment by Synchro** [comment]
I think I got that from SASS, no idea why it was chosen as their default.

**Comment by lukeapage** [comment]
I'll look at hsv next and pull it. This is pulled.. although until reference is referenced its invisble..

**Pull request closed without merging**
