### PR TITLE
Added "try it now!" link to nav bar

### PR DESCRIPTION
**Pull request by bfricka**
Per conversation on [this issue](https://github.com/cloudhead/less.js/issues/1100#issuecomment-11988265).

### CODE REVIEW

**Comment by lukeapage** [comment]
Thanks for your work. This is pulled and now live.

**Comment by bfricka** [comment]
Happy to help, and I have plenty of plans to improve.  Feel free to enter the discussion or contribute. :)

**Comment by lukeapage** [comment]
@brian-frichette I've got enough to do with less.js core and documentation!

**Comment by matthew-dean** [comment]
I would suggest removing the male-centric copy of the LESS2CSS tool.

`"@theGoodThings: ~".food, .beer, .ladies, .sleep, .javascript";`

It's cute, but not all web developers are male.

**Comment by lukeapage** [comment]
I think they added that later. Not only is it male centric but we would
rather not encourage JavaScript use.. plenty of other language features
that could be showed off.

**Comment by bfricka** [comment]
Agreed. I will take care of this today.

**Pull request closed without merging**
